import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        This is the website of Melvin Rinkleff
        <br />
        Melvin Rinkleff
        <br />
        Thomasstraße 75
        <br />
        12053 Berlin
      </div>
    </>
  )
}
